version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Containerfile
    container_name: preguntame_backend
    env_file:
      - ./backend/.env
    networks:
      - default
    depends_on:
      - db
    volumes:
      - ./backend/media:/app/media

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: preguntas
      POSTGRES_PASSWORD: Decor2026*
      POSTGRES_DB: preguntas_frecuentes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

  frontend:
    build:
      context: ./frontend/preguntas_frecuentes
      dockerfile: Containerfile
    container_name: preguntame_frontend
    # ports:
    #   - "5046:80"  # Quitado para que solo nginx exponga el 5046
    depends_on:
      - backend
    networks:
      - default

  nginx:
    image: nginx:alpine
    container_name: preguntame_nginx
    ports:
      # - "80:80"  # Comentado para evitar conflicto de puerto
      - "443:443"
      - "5046:5046"
      - "5047:5047"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/ssl:ro
      - ./staticfiles:/var/www/static
      - ./media:/var/www/media
    depends_on:
      - backend
      - frontend
    networks:
      - default

volumes:
  postgres_data: 