version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Containerfile
    container_name: preguntame_backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    networks:
      - default

  frontend:
    build:
      context: ./frontend/preguntas_frecuentes
      dockerfile: Containerfile
    container_name: preguntame_frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - default

# Si usas base de datos, descomenta y configura:
#  db:
#    image: postgres:13
#    container_name: postgres_db
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: preguntas_frecuentes
#    ports:
#      - "5432:5432"
#    networks:
#      - default

#volumes:
  #postgres_data: {} 