version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Containerfile
    container_name: preguntame_backend
    env_file:
      - ./backend/.env
    ports:
      - "5047:8000"
    networks:
      - default
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: preguntas
      POSTGRES_PASSWORD: una_contraseña_segura
      POSTGRES_DB: preguntas_frecuentes
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

  frontend:
    build:
      context: ./frontend/preguntas_frecuentes
      dockerfile: Containerfile
    container_name: preguntame_frontend
    ports:
      - "5046:80"
    depends_on:
      - backend
    networks:
      - default

volumes:
  postgres_data: 