## Usa una imagen base ligera de Python
FROM python:3.10-slim

## Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

## Copia el archivo de requisitos primero para aprovechar el cache de Podman
COPY requirements.txt /app/

## Instala dependencias del sistema necesarias para python-ldap y Pillow
RUN apt-get update && apt-get install -y gcc libldap2-dev libsasl2-dev python3-dev libssl-dev && rm -rf /var/lib/apt/lists/*

## Instala las dependencias
RUN pip install --no-cache-dir -r requirements.txt

## Copia el script de entrada y dale permisos de ejecución
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh


## Copia el resto del código de la aplicación
COPY . /app/

# Configura la variable de entorno DJANGO_SETTINGS_MODULE
ENV DJANGO_SETTINGS_MODULE=Preguntas_frecuentes.settings

## Ejecuta las migraciones de la base de datos (opcional)
# RUN python manage.py migrate

## Recolecta archivos estáticos (opcional)
RUN python manage.py collectstatic --noinput

## Expone el puerto en el que Gunicorn escuchará
EXPOSE 8000

## Usa el script como ENTRYPOINT para iniciar la aplicación
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]