# Etapa 1: Construir la aplicación Vue.js
FROM node:lts-alpine as builder
WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install

COPY . ./

RUN npm run build
RUN echo "Contenido de /app/public:" && ls -lh /app/public && echo "Contenido de /app/dist:" && ls -lh /app/dist && echo "Archivos en public:" && find /app/public

# Etapa 2: Servir los archivos estáticos con Nginx
FROM nginx:alpine
# Copia los archivos construidos desde la etapa 'builder'
COPY --from=builder /app/dist /usr/share/nginx/html

# Copia tu configuración personalizada de Nginx (creada en el paso anterior)
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Nginx escuchará en el puerto 80 dentro del contenedor, como se define en nginx.conf
# El docker-compose.yml mapea el puerto 3000 del host al 80 del contenedor.
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
